version: 0.0
os: linux
files:
  - source: /
    destination: /var/manager/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 30
      runas: root
